Revert "intel/package.use: dev-util/electron -system-libvpx"
Well,
../../third_party/webrtc/modules/video_coding/codecs/vp9/vp9_impl.cc:452:31:
error: ‘VP9E_SET_ROW_MT’ was not declared in this scope

(after this change) so there's no point in doing this.

This reverts commit 9df638137940d2e27b45bb026df71a611d425e85.