intel/package.use: www-client/firefox -system-av1
Otherwise media-libs/libaom is pulled which does not build:

Gentoo bug 671340: media-libs/libaom-1.0.0 USE="cpu_flags_x86_sse2 -cpu_flags_x86_ssse3" - libaom.so.0: undefined reference to `aom_sad4xh_sse2'